### ISSUE TITLE
Error on default tuple arguments

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-python#123]
```
def comp_args((a, b)=(3, 4)):
    return a, b
```

```
(module [0, 0] - [2, 0]
  (function_definition [0, 0] - [1, 15]
    name: (identifier [0, 4] - [0, 13])
    parameters: (parameters [0, 13] - [0, 28]
      (ERROR [0, 14] - [0, 21]
        (tuple_pattern [0, 14] - [0, 20]
          (identifier [0, 15] - [0, 16])
          (identifier [0, 18] - [0, 19])))
      (tuple_pattern [0, 21] - [0, 27]
        (ERROR [0, 22] - [0, 26]
          (integer [0, 22] - [0, 23])
          (integer [0, 25] - [0, 26]))))
    body: (block [1, 4] - [1, 15]
      (return_statement [1, 4] - [1, 15]
        (expression_list [1, 11] - [1, 15]
          (identifier [1, 11] - [1, 12])
          (identifier [1, 14] - [1, 15]))))))
fail/DefaultTupleArguments.py	0 ms	(ERROR [0, 14] - [0, 21])
```

**Comment by jasontatton** [comment]
Is this valid Python though? It's not valid in 3.10, has this changed in 3.11 or 3.12?

**Comment by amaanq** [comment]
It's valid in python 2

**Comment by jasontatton** [comment]
This is problematic because now we have a grammar definition which has invalid features for Python 3 (such as this) and invalid features for Python 2. @maxbrunsfeld has consideration been given to forking [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python) into the likes of: tree-sitter-python-2.7, tree-sitter-python-3.10, tree-sitter-python-3.12 etc?

**Comment by amaanq** [comment]
I'm curious as to how it's problematic, I hope you're not writing some sort of preprocessor/runtime backend with this

**Comment by jasontatton** [comment]
To provide some context here, at Meta, we are using tree-sitter within [Pyre](https://github.com/facebook/pyre-check) via the [errpy project](https://github.com/facebook/errpy) to parse the entirety of the Meta Python codebase (~1.6m python files and ~200m lines of code), in order to enable company wide code modifications and drive our development tools. We are targeting Python 3.10 compatibility (having recently upgraded the codebase from 3.8) and will next be looking at 3.12.

It is important that when parsing we avoid accepting code which is invalid as par the 3.10 specification. Hence why being able to accept legacy syntax like this is problematic.

If needed we can help we can assist in the process of forking tree-sitter-python into the likes of tree-sitter-python-3.10 - I expect it would mostly consist of stripping out features such as this one and the likes of the print and exec statements etc.

**Comment by jasontatton** [comment]
Though it would potentially mean more work from a maintenance perspective as now more than one variant of tree-sitter-python would need to be maintained. I am curios to understand how/if this problem of multiple language versions has been solved for other parsers.

**Comment by amaanq** [comment]
Hm, I'm unsure of another language besides Cairo (for which I wrote the grammar here: https://github.com/amaanq/tree-sitter-cairo/blob/master/grammar.js) that has distinct non-backwards compatible language changes across versions

I don't think forking would be best, but perhaps conditional compilation features in the grammar could be used to get the results you'd want
