### ISSUE TITLE
Issue with docstrings using google style format

### ISSUE THREAD

**Issue by AckslD** [tree-sitter/tree-sitter-python#137]
I'm currently on latest neovim nightly and latest `nvim-treesitter` and am having some issues with google style doc-strings which I think is best illustrated with the gif below:

![treesitter](https://user-images.githubusercontent.com/23341710/141189174-cd1c73ad-ca81-45cf-b144-78fc622af28f.gif)

It seems to be very picky with whitespace and removing it before the first column makes the error go away but sometimes in more complicated examples this also doesn't work.

Let me know if you need some additional information or explanation of the issue.

**Comment by stsewd** [comment]
Hi, this should have been reported to https://github.com/nvim-treesitter/nvim-treesitter, but anyway this is because docstrings are being parsed as rst (I have a PR to make this configurable https://github.com/nvim-treesitter/nvim-treesitter/pull/1240). But that content is valid rst, there is a bug already reported at https://github.com/stsewd/tree-sitter-rst/issues/16.

**Comment by AckslD** [comment]
Oh I see, sorry about that and thanks for the information! :)
