### ISSUE TITLE
highlighting changes after switching to tree-sitter (`is` and `yield`)

### ISSUE THREAD

**Issue by FlorianLudwig** [tree-sitter/tree-sitter-python#18]
Example:
```python
if something is None:
  yield None
````
With tree-sitter `is` and `yield` are not highlighted as before

**Comment by maxbrunsfeld** [comment]
Thanks for the report @FlorianLudwig! For context, the actual syntax highlighting is controlled by the Atom package that *uses* this parser: [language-python](https://github.com/atom/language-python). Specifically, the [scopes](https://github.com/atom/language-python/blob/master/grammars/tree-sitter-python.cson#L42-L93) section of the grammar. That object contains a mapping of CSS selectors (selecting nodes in the syntax tree) to classes that should be applied to those nodes. It looks like we just need to add a mapping for `yield` and `is`.

If you're interested in opening a PR that fixes this, I'd definitely merge it. Otherwise, I can add these things shortly.

**Comment by maxbrunsfeld** [comment]
Fixed via https://github.com/atom/language-python/commit/b1fb6eadd4ab661348ad635ee469a0f32eba03a7.
