### ISSUE TITLE
Autoindent does not work for first line in block

### ISSUE THREAD

**Issue by Philogy** [tree-sitter/tree-sitter-python#183]
Unsure what exactly causes this but indentation via python tree sitter does not seem to work correctly. Specifically when defining a new function, if-clause or for-loop pressing enter doesn't does not go to the correct indentation level at first, only once something is already written in the block at the level will it correctly autoindent.

I'm quite sure the issue stems from python tree sitter because:
1. Tree sitter based indent works in other languages
2. Disabling only python in my treesitter config via `indent = { enable = true, disable = { 'python' } },` solves the issue

**Comment by theHamsta** [comment]
Please file at https://github.com/nvim-treesitter/nvim-treesitter. This repo is not related to Neovim

**Comment by Philogy** [comment]
That's what I'm trying to say, the issue seems to stem from `tree-sitter-python` not Neovim

**Comment by maxbrunsfeld** [comment]
This repository is about providing parse trees from source code. If you're getting an unexpected parse tree from a given source file, and you can explain why the parse tree is wrong on its own terms, then report the issue here. The issue you're describing should be reported on `nvim-treesitter`, like @theHamsta  mentioned.
