### ISSUE TITLE
Unexpected error recovery for python

### ISSUE THREAD

**Issue by bloff** [tree-sitter/tree-sitter-python#62]
Just playing around on the playground (https://tree-sitter.github.io/tree-sitter/playground), the following python code says for is an identifier, and marks x as the error, instead of the other way around.

```python
def func(x, list):
   if for x in list:
      print(x)
```

**Comment by maxbrunsfeld** [comment]
Just to clarify, given that this code example is invalid, you're reporting that the way that Tree-sitter recovered from the error is not what you'd have expected; is that right?

Here's the tree that I get:

```
(module [0, 0] - [4, 0]
  (function_definition [0, 0] - [2, 14]
    name: (identifier [0, 4] - [0, 8])
    parameters: (parameters [0, 8] - [0, 17]
      (identifier [0, 9] - [0, 10])
      (identifier [0, 12] - [0, 16]))
    body: (block [1, 3] - [2, 14]
      (if_statement [1, 3] - [2, 14]
        condition: (comparison_operator [1, 6] - [1, 19]
          (identifier [1, 6] - [1, 9])
          (ERROR [1, 10] - [1, 11]
            (identifier [1, 10] - [1, 11]))
          (identifier [1, 15] - [1, 19]))
        consequence: (block [2, 6] - [2, 14]
          (expression_statement [2, 6] - [2, 14]
            (call [2, 6] - [2, 14]
              function: (identifier [2, 6] - [2, 11])
              arguments: (argument_list [2, 11] - [2, 14]
                (identifier [2, 12] - [2, 13])))))))))
```

I would consider this a decent error recovery; it's still recognizing the `if_statement`, but dropping the word `x`.

It is true that `for` is a keyword, so it would be better to mark *that* as the error instead of the `x`. The reason that doesn't happen right now is that all keywords in Tree-sitter grammars are basically *contextual* keywords - words that have special meaning in certain contexts. After the word `if`, the word `for` has no special meaning, so Tree-sitter treats it as any other identifier.

In the future, I might add a feature to Tree-sitter to allow a grammar author to tune error recovery in this regard. In this case, it would allow the Python grammar to indicate that `for` is basically a global keyword. But I haven't fully designed how this feature would work.

**Comment by bloff** [comment]
Yup, that is what I meant. Python itself will mark 'for' as the unexpected syntax. I suppose this isn't a very serious problem, I was surprised, is all :-)

tree-sitter is really impressive, by the way.
