### ISSUE TITLE
Is it possible to provide a condensed/readable version of grammar.json (similar to the python reference grammar format)

### ISSUE THREAD

**Issue by mbreslav** [tree-sitter/tree-sitter-python#75]
I am new to tree-sitter and my understanding is that the python grammar specified in _grammar.json_ is based on the Python reference grammar. However, it isn't exactly 1 to 1 with the reference grammar, so I've been wondering what the differences are. I realize that the differences are reflected in _grammar.json_ , but that file is difficult to read to get a summary view.

This leads me to ask, is it possible to provide the tree-sitter python grammar in a more readable and condensed format, similar to how the Python reference is presented ([https://docs.python.org/3.8/reference/grammar.html](https://docs.python.org/3.8/reference/grammar.html))?

If it can't be provided, do you know if it is relatively trivial to generate, or are there some theoretical reasons it couldn't be converted into something like EBNF?

Thanks

**Comment by patrickt** [comment]
I think this request would best be made in the tree-sitter repository. However, I am doubtful as to whether this is feasible, mainly because there really isn’t a more suitable high-level description of a grammar than `grammar.js` (note: are you reading `grammar.json`, or `grammar.js`): the JS DSL is able to express things like comma-separated lists in a manner that is a lot more readable than your standard EBNF grammar.
